services:
  api:
    build: .
    container_name: api
    expose:
      - "8000"
    env_file:
      - .env
    mem_limit: 3072M
    cpus: 4.0
    restart: always
    volumes:
      - models_data:/app/models
      - ./uvicorn_config.py:/app/uvicorn_config.py
    command: >
      sh -c "python /app/download_model.py && python /app/uvicorn_config.py"
    
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    mem_limit: 512M
    cpus: 0.5
    restart: always
    
volumes:
  models_data:
  mongo-data:
